# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

from enum import IntEnum
from typing import Any, Callable, Sequence

class WholeGraphErrorCode(IntEnum):
    Success = ...
    UnknowError = ...
    NotImplemented = ...
    LogicError = ...
    CUDAError = ...
    CommunicationError = ...
    InvalidInput = ...
    InvalidValue = ...
    OutOfMemory = ...
    NotSupported = ...

class WholeGraphMemoryType(IntEnum):
    MtNone = ...
    MtContinuous = ...
    MtDistributed = ...

class WholeGraphMemoryLocation(IntEnum):
    MlNone = ...
    MlDevice = ...
    MlHost = ...

class WholeGraphDistributedBackend(IntEnum):
    DbNone = ...
    DbNCCL = ...

class WholeGraphLogLevel(IntEnum):
    LevFatal = ...
    LevError = ...
    LevWarn = ...
    LevInfo = ...
    LevDebug = ...
    LevTrace = ...

class WholeGraphMemoryAllocType(IntEnum):
    MatNone = ...
    MatDevice = ...
    MatHost = ...
    MatPinned = ...

class WholeGraphDataType(IntEnum):
    DtUnknown = ...
    DtFloat = ...
    DtHalf = ...
    DtDouble = ...
    DtBF16 = ...
    DtInt = ...
    DtInt64 = ...
    DtInt16 = ...
    DtInt8 = ...
    DtCount = ...

class WholeGraphViewType(IntEnum):
    VtNone = ...
    VtLocal = ...
    VtGlobal = ...
    VtRemote = ...

class WholeGraphAccessType(IntEnum):
    AtNone = ...
    AtReadOnly = ...
    AtReadWrite = ...

class WholeGraphOptimizerType(IntEnum):
    OptNone = ...
    OptSgd = ...
    OptLazyAdam = ...
    OptRmsProp = ...
    OptAdaGrad = ...

class DLDeviceType(IntEnum):
    kDLCPU = ...
    kDLCUDA = ...
    kDLCUDAHost = ...

class PyMemoryAllocType:
    def __init__(self) -> None: ...
    def set_type(self, new_type: WholeGraphMemoryAllocType) -> None: ...
    def get_type(self) -> int: ...
    def set_ctype(self, alloc_type: int) -> None: ...
    def get_ctype(self) -> int: ...

class GlobalContextWrapper:
    def __init__(self) -> None: ...
    def create_context(
        self,
        temp_create_context_fn: Callable[[Any], Any],
        temp_destroy_context_fn: Callable[[Any, Any], Any],
        temp_malloc_fn: Callable[[tuple[int, ...], int, int, Any, Any], int],
        temp_free_fn: Callable[[Any, Any], Any],
        temp_global_context: Any | None,
        output_malloc_fn: Callable[[tuple[int, ...], int, int, Any, Any], int],
        output_free_fn: Callable[[Any, Any], Any],
        output_global_context: Any | None,
    ) -> None: ...
    def get_env_fns(self) -> int: ...

class PyWholeGraphUniqueID:
    def __init__(self) -> None: ...
    def __len__(self) -> int: ...
    def __dlpack__(self, stream: Any | None = None) -> Any: ...
    def __dlpack_device__(self) -> tuple[int, int]: ...

class PyWholeGraphComm:
    def __init__(self) -> None: ...
    def get_c_handle(self) -> int: ...
    def support_type_location(
        self,
        memory_type: WholeGraphMemoryType,
        memory_location: WholeGraphMemoryLocation,
    ) -> bool: ...
    def get_rank(self) -> int: ...
    def get_size(self) -> int: ...
    def get_clique_info(self) -> tuple[bool, int, int, int, int, int]: ...
    def barrier(self) -> None: ...
    def get_distributed_backend(self) -> WholeGraphDistributedBackend: ...
    def set_distributed_backend(
        self, distributed_backend: WholeGraphDistributedBackend
    ) -> None: ...

class PyWholeGraphHandle:
    def __init__(self) -> None: ...
    def get_c_handle(self) -> int: ...
    def get_communicator(self) -> PyWholeGraphComm: ...
    def get_memory_type(self) -> WholeGraphMemoryType: ...
    def get_memory_location(self) -> WholeGraphMemoryLocation: ...
    def get_global_flatten_tensor(
        self,
        import_dlpack_fn: Callable[[Any], Any],
        data_type: WholeGraphDataType,
        view_from_device: WholeGraphMemoryLocation,
        view_from_device_id: int,
    ) -> tuple[Any, int]: ...
    def get_local_flatten_tensor(
        self,
        import_dlpack_fn: Callable[[Any], Any],
        data_type: WholeGraphDataType,
        view_from_device: WholeGraphMemoryLocation,
        view_from_device_id: int,
    ) -> tuple[Any, int]: ...
    def from_filelist(
        self,
        memory_offset: int,
        memory_entry_size: int,
        file_entry_size: int,
        round_robin_size: int,
        file_list: Sequence[str] | str,
    ) -> None: ...
    def to_file(
        self,
        memory_offset: int,
        memory_entry_size: int,
        file_entry_size: int,
        file_name: str,
    ) -> None: ...

class PyWholeGraphTensorDescription:
    def __init__(self) -> None: ...
    def set_dtype(self, dtype: WholeGraphDataType) -> None: ...
    def set_shape(self, shape: Sequence[int]) -> None: ...
    def set_stride(self, strides: Sequence[int]) -> None: ...
    def set_storage_offset(self, storage_offset: int) -> None: ...
    @property
    def dtype(self) -> WholeGraphDataType: ...
    def dim(self) -> int: ...
    @property
    def shape(self) -> tuple[int, ...]: ...
    def stride(self) -> tuple[int, ...]: ...
    def storage_offset(self) -> int: ...

class WrappedLocalTensor:
    def __init__(self) -> None: ...
    def wrap_tensor(
        self, py_desc: PyWholeGraphTensorDescription, data_ptr: int
    ) -> WrappedLocalTensor: ...
    def get_c_handle(self) -> int: ...

class PyWholeGraphFlattenDlpack:
    def __init__(self) -> None: ...
    def __len__(self) -> int: ...
    def set_view_device(
        self, device_type: WholeGraphMemoryLocation, device_id: int
    ) -> None: ...
    def get_view(
        self,
        handle: PyWholeGraphHandle,
        data_type: WholeGraphDataType,
        view_type: WholeGraphViewType,
        target_rank: int,
    ) -> tuple[int, int]: ...
    @property
    def ptr(self) -> int: ...
    @property
    def __cuda_array_interface__(self) -> dict[str, Any]: ...
    def __dlpack__(self, stream: Any | None = None) -> Any: ...
    def __dlpack_device__(self) -> tuple[int, int]: ...

class PyWholeGraphTensor:
    def __init__(self) -> None: ...
    def get_c_handle(self) -> int: ...
    def get_wholegraph_handle(self) -> PyWholeGraphHandle: ...
    @property
    def dtype(self) -> WholeGraphDataType: ...
    def dim(self) -> int: ...
    @property
    def shape(self) -> tuple[int, ...]: ...
    def stride(self) -> tuple[int, ...]: ...
    def storage_offset(self) -> int: ...
    def get_local_entry_count(self) -> int: ...
    def get_local_entry_start(self) -> int: ...
    def get_sub_tensor(self, starts: Sequence[int], ends: Sequence[int]) -> PyWholeGraphTensor: ...
    def get_tensor_in_window(
        self, flatten_tensor: Any, storage_window_offset: int
    ) -> tuple[Any, int]: ...
    def get_local_tensor(
        self,
        import_dlpack_fn: Callable[[Any], Any],
        view_from_device: WholeGraphMemoryLocation,
        view_from_device_id: int,
    ) -> tuple[Any, int]: ...
    def get_global_tensor(
        self,
        import_dlpack_fn: Callable[[Any], Any],
        view_from_device: WholeGraphMemoryLocation,
        view_from_device_id: int,
    ) -> Any: ...
    def from_filelist(
        self, file_list: Sequence[str] | str, round_robin_size: int = 0
    ) -> None: ...
    def to_file(self, filename: str) -> None: ...

class WholeGraphCachePolicy:
    def __init__(self) -> None: ...
    def create_policy(
        self,
        cache_comm: PyWholeGraphComm,
        memory_type: WholeGraphMemoryType,
        memory_location: WholeGraphMemoryLocation,
        access_type: WholeGraphAccessType,
        ratio: float,
    ) -> None: ...
    def destroy_policy(self) -> None: ...
    def get_c_handle(self) -> int: ...

class PyWholeGraphEmbedding:
    def __init__(self) -> None: ...
    def get_c_handle(self) -> int: ...
    def get_embedding_tensor(self) -> PyWholeGraphTensor: ...
    def get_optimizer_state_names(self) -> list[str]: ...
    def get_optimizer_state(self, name: str) -> PyWholeGraphTensor: ...
    def writeback_all_cache(self, stream_int: int) -> None: ...
    def drop_all_cache(self, stream_int: int) -> None: ...
    def destroy_embedding(self) -> None: ...

class WholeGraphOptimizer:
    def __init__(self) -> None: ...
    def create_optimizer(
        self,
        optimizer_type: WholeGraphOptimizerType,
        param_dict: dict[str, float],
    ) -> None: ...
    def add_embedding(self, embedding: PyWholeGraphEmbedding) -> None: ...
    def destroy_optimizer(self) -> None: ...
    def get_c_handle(self) -> int: ...

def init(flags: int, log_level: WholeGraphLogLevel = ...) -> None: ...
def finalize() -> None: ...
def create_unique_id() -> PyWholeGraphUniqueID: ...
def get_type_string(data_type: WholeGraphDataType) -> str: ...
def create_communicator(
    py_uid: PyWholeGraphUniqueID, world_rank: int, world_size: int
) -> PyWholeGraphComm: ...
def destroy_communicator(py_comm: PyWholeGraphComm) -> None: ...
def split_communicator(
    comm: PyWholeGraphComm, color: int, key: int
) -> PyWholeGraphComm: ...
def communicator_set_distributed_backend(
    py_comm: PyWholeGraphComm,
    distributed_backend: WholeGraphDistributedBackend,
) -> None: ...
def equal_partition_plan(entry_count: int, world_size: int) -> int: ...
def malloc(
    total_size: int,
    py_comm: PyWholeGraphComm,
    memory_type: WholeGraphMemoryType,
    memory_location: WholeGraphMemoryLocation,
    data_granularity: int,
    rank_entry_partition: Any | None = None,
) -> PyWholeGraphHandle: ...
def free(handle: PyWholeGraphHandle) -> None: ...
def create_wholegraph_array(
    dtype: WholeGraphDataType,
    size: int,
    comm: PyWholeGraphComm,
    mem_type: WholeGraphMemoryType,
    mem_location: WholeGraphMemoryLocation,
    tensor_entry_partition: Any | None = None,
) -> PyWholeGraphTensor: ...
def create_wholegraph_matrix(
    dtype: WholeGraphDataType,
    row: int,
    column: int,
    stride: int,
    comm: PyWholeGraphComm,
    mem_type: WholeGraphMemoryType,
    mem_location: WholeGraphMemoryLocation,
    tensor_entry_partition: Any | None = None,
) -> PyWholeGraphTensor: ...
def create_wholegraph_tensor(
    tensor_description: PyWholeGraphTensorDescription,
    comm: PyWholeGraphComm,
    mem_type: WholeGraphMemoryType,
    mem_location: WholeGraphMemoryLocation,
    tensor_entry_partition: Any | None = None,
) -> PyWholeGraphTensor: ...
def make_tensor_as_wholegraph(
    tensor_description: PyWholeGraphTensorDescription, data_ptr: int
) -> PyWholeGraphTensor: ...
def make_handle_as_wholegraph(
    tensor_description: PyWholeGraphTensorDescription, handle: PyWholeGraphHandle
) -> PyWholeGraphTensor: ...
def destroy_wholegraph_tensor(wholegraph_tensor: PyWholeGraphTensor) -> None: ...
def create_non_cache_policy() -> WholeGraphCachePolicy: ...
def create_embedding(
    tensor_description: PyWholeGraphTensorDescription,
    comm: PyWholeGraphComm,
    memory_type: WholeGraphMemoryType,
    memory_location: WholeGraphMemoryLocation,
    cache_policy: WholeGraphCachePolicy,
    embedding_entry_partition: Any | None = None,
    user_defined_sms: int = -1,
    round_robin_size: int = 0,
) -> PyWholeGraphEmbedding: ...
def wholegraph_env_test_op(
    input_tensor: WrappedLocalTensor,
    output_fixed_tensor: WrappedLocalTensor,
    output_variable_device_tensor_handle: int,
    output_variable_pinned_tensor_handle: int,
    output_variable_host_tensor_handle: int,
    output_variable_entry_count: int,
    p_env_fns_int: int,
    stream_int: int,
) -> None: ...
def wholegraph_gather_op(
    wholegraph_tensor: PyWholeGraphTensor,
    indices_tensor: WrappedLocalTensor,
    output_tensor: WrappedLocalTensor,
    p_env_fns_int: int,
    stream_int: int,
) -> None: ...
def wholegraph_scatter_op(
    input_tensor: WrappedLocalTensor,
    indices_tensor: WrappedLocalTensor,
    wholegraph_tensor: PyWholeGraphTensor,
    p_env_fns_int: int,
    stream_int: int,
) -> None: ...
def EmbeddingGatherForward(
    embedding: PyWholeGraphEmbedding,
    indices_tensor: WrappedLocalTensor,
    output_tensor: WrappedLocalTensor,
    adjust_cache: bool,
    p_env_fns_int: int,
    stream_int: int,
) -> None: ...
def EmbeddingGatherGradientApply(
    embedding: PyWholeGraphEmbedding,
    indices_tensor: WrappedLocalTensor,
    grads_tensor: WrappedLocalTensor,
    adjust_cache: bool,
    lr: float,
    p_env_fns_int: int,
    stream_int: int,
) -> None: ...
def csr_unweighted_sample_without_replacement(
    wg_csr_row_ptr_tensor: PyWholeGraphTensor,
    wg_csr_col_ptr_tensor: PyWholeGraphTensor,
    center_nodes_tensor: WrappedLocalTensor,
    max_sample_count: int,
    output_sample_offset_tensor: WrappedLocalTensor,
    output_dest_memory_context: int,
    output_center_localid_memory_context: int,
    output_edge_gid_memory_context: int,
    random_seed: int,
    p_env_fns_int: int,
    stream_int: int,
) -> None: ...
def csr_weighted_sample_without_replacement(
    wg_csr_row_ptr_tensor: PyWholeGraphTensor,
    wg_csr_col_ptr_tensor: PyWholeGraphTensor,
    wg_csr_weight_ptr_tensor: PyWholeGraphTensor,
    center_nodes_tensor: WrappedLocalTensor,
    max_sample_count: int,
    output_sample_offset_tensor: WrappedLocalTensor,
    output_dest_memory_context: int,
    output_center_localid_memory_context: int,
    output_edge_gid_memory_context: int,
    random_seed: int,
    p_env_fns_int: int,
    stream_int: int,
) -> None: ...
def host_generate_random_positive_int(
    random_seed: int, subsequence: int, output: WrappedLocalTensor
) -> None: ...
def host_generate_exponential_distribution_negative_float(
    random_seed: int, subsequence: int, output: WrappedLocalTensor
) -> None: ...
def append_unique(
    target_nodes_tensor: WrappedLocalTensor,
    neighbor_nodes_tensor: WrappedLocalTensor,
    output_unique_node_memory_context: int,
    output_neighbor_raw_to_unique_mapping_tensor: WrappedLocalTensor,
    p_env_fns_int: int,
    stream_int: int,
) -> None: ...
def add_csr_self_loop(
    csr_row_ptr_tensor: WrappedLocalTensor,
    csr_col_ptr_tensor: WrappedLocalTensor,
    output_csr_row_ptr_tensor: WrappedLocalTensor,
    output_csr_col_ptr_tensor: WrappedLocalTensor,
    stream_int: int,
) -> None: ...
def fork_get_gpu_count() -> int: ...
def load_wholegraph_handle_from_filelist(
    wholegraph_handle_int_ptr: int,
    memory_offset: int,
    memory_entry_size: int,
    file_entry_size: int,
    round_robin_size: int,
    file_list: Sequence[str] | str,
) -> None: ...
def store_wholegraph_handle_to_file(
    wholegraph_handle_int_ptr: int,
    memory_offset: int,
    memory_entry_size: int,
    file_entry_size: int,
    file_name: str,
) -> None: ...
